name: primera prueba

on:
  push:
    branches:
      - main

jobs:

  deploy: 
    runs-on: ubuntu-latest
    services:  
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with: 
          node-version: 20  
      - name: install dependency
        run: npm install
      - name: build
        run: npm run start