name: primera prueba

on:
  push:
    branches:
      - main
  pull_request: 
    branches: [main]
    types: [opened,synchronize]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: cancel builds redundant
        uses: styfle/cancel-workflow-action
        with: 
          access_token: ${{github.token}}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with: 
          node-version: 20  
      - name: install dependency
        run: npm ci 
      - name: build
        run: npm run build
      - name: test
        run: npm run test