name: primera prueba

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu@latest
    steps:
      - uses: action/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with: 
          node-version: '20.9.0'  
      - name: install dependency
        run: npm ci